config/routes.rb
Rails.application.routes.draw do
  root   'posts#index'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :posts, only: [:new, :create, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts
  attr_accessor :remember_token
  before_create :remember
  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  has_secure_password

  # Returns a random token.
  def self.new_token
    Digest::SHA1.hexdigest SecureRandom.urlsafe_base64.to_s
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    self.remember_digest = remember_token
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :sign_in?, only: %i[new create]
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    @post.user_id = current_user.id

    @post.save

    redirect_to root_url
  end

  def index
    @posts = Post.all
  end

  private

  def sign_in?
    redirect_to login_path unless logged_in?
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      remember(user)
      flash[:info] = 'User Logged in'
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    if logged_in?
      log_out
      flash[:info] = 'User logged out.'
    else
      flash[:info] = "User wasn't even logged in."
    end
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def author(user_id)
    User.find(user_id).name
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end

  def current_user=(user)
    @current_user = user
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_header.html.erb
<header >
  <div >
    <nav>
      <ul >
       <% if logged_in? %>
          <li class="h_li">
          <%= link_to 'Create new posts', new_post_path, class: 'new_article h_a' %>
          </li>
              <li class="h_li">
                <%= link_to "Sign out", logout_path, method: :delete, class: 'new_article h_a' %>
              </li>
        <% else %>
          <li class="h_li"><%= link_to "Sign in", login_path, class: 'new_article h_a' %></li>
        <% end %>
          <li class="h_li">
          <%= link_to 'All posts', root_path, class: 'new_article h_a' %>
          </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <p class="flash"><%= message %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>Members Only</h1>

<ul id="posts">
  <% @posts.each do |post| %>
    <li>
      <b>Title : <%= post.title %> 
      <%= "----- Author: #{author post.user_id}" if logged_in? %></b>
      <p>body : <%= post.body %></p>
    </li>

  <% end %>
</ul>

app/views/posts/new.html.erb
<%= form_for(@post) do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :body %>
    <%= f.text_area :body %>

    <%= f.submit "Create Post" %>
  <% end %>